language: shell
services: docker
os:
- linux-ppc64le
- linux
sudo: false

env:
  global:
    - REPO="${DOCKER_USERNAME}/tesseract4cmp"
  matrix:
    - RELEASE=16.04
    - RELEASE=18.04
    - RELEASE=latest

# DOCKER_USERNAME and DOCKER_PASSWORD need to be secure environment variables either above
# or in the settings within travis.

script:
- ./dockerfile.build.sh
- ./scripts/3-run-new-container.sh
- ./scripts/4-update-src.sh 
- ./scripts/5-compile-src.sh
- ./scripts/6-test-ocr.sh
- ./scripts/7-build-pkg.sh
- ./scripts/2-remove-container.sh
- docker tag tesseractshadow/tesseract4cmp:latest "${REPO}:${RELEASE}_$(uname -m)"

after_success:
- |
   if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]] &&
      [[ "$TRAVIS_BRANCH" = "master" ]]; then
     docker images
     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
     docker push "${REPO}:${RELEASE}_$(uname -m)"
   fi

jobs:
  include:
    - stage: build_multi_arch_docker_image
      # only ppc64le currently has a docker new enough to support experimental manifests
      os: linux-ppc64le
      # minimise things that the stage doesn't require.
      before_install: true
      install: true
      after_success: true
      script:
      - |
         if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]] &&
            [[ "$TRAVIS_BRANCH" = "master" ]]; then
           mkdir -p ~/.docker
           echo '{ "experimental" : "enabled" }' > ~/.docker/config.json
           echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           docker manifest create --amend "${REPO}:${RELEASE}" "${REPO}:${RELEASE}_x86_64" "${REPO}:${RELEASE}_ppc64le"
           docker manifest inspect "${REPO}:${RELEASE}"
           docker manifest push    "${REPO}:${RELEASE}"
         fi

# vim:set et ts=2 sw=2:
